language: python
python:
  - "3.7"
services:
  - docker
before_script:
  - pip install docker-compose
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
script:
  - docker-compose build
  - docker-compose run api sh -c  "pytest -v . && flake8"