version: '3.7'

services:
  api:
    build: ./services/api
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev